# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "Testing prompts for a case extraction tool that pulls case citations out of legal briefs and opinions."

prompts:
  #- prompts/prompts.py:basic_initial_prompt
  #- prompts/prompts.py:better_initial_prompt_1
  #- prompts/prompts.py:better_initial_prompt_2
  #- prompts/prompts.py:refactored_prompt_1
  - prompts/prompts.py:refactored_prompt_2
  - prompts/prompts.py:refactored_prompt_3
  

providers:
  - id: "anthropic:messages:claude-3-7-sonnet-latest"
    config:
      max_tokens: 4096
  - id: "anthropic:messages:claude-3-5-haiku-latest"
    config:
      max_tokens: 4096
  - id: "mistral:mistral-large-latest"
    config:
      max_tokens: 4096
  - id: "mistral:mistral-small-latest"
    config:
      max_tokens: 4096
  

tests:
  - description: "Returns accurate count of citations in given text file."
    vars:
      brief: file://./test-set/text-files/doe-v-bluecross-order-on-misc-relief.txt
    assert:
      - type: equals
        value: "16"
        transform: file://./tests/get_count.py:get_count
    
