# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "Testing prompts for a case extraction tool that pulls case citations out of legal briefs and opinions."

prompts:
  - prompts/prompts.py:basic_initial_prompt
  - prompts/prompts.py:better_initial_prompt_1
  - prompts/prompts.py:better_initial_prompt_2
  

providers:
  - "anthropic:messages:claude-3-5-haiku-latest"
  - "mistral:mistral-small-latest"
  

tests:
  - description: "Returns accurate count of citations in given text file."
    vars:
      brief: file://./test-set/text-files/doe-v-bluecross-order-on-misc-relief.txt
    options:
      transform: file://./tests/get_count.py:get_count
    assert:
      - type: equals
        value: "19"
    
